CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100),
    amount NUMBER(10,2),
    type VARCHAR2(20),
    date_added DATE DEFAULT SYSDATE
);

